include("v_motus_cvars.lua")

if CLIENT then
	hook.Add("PopulateToolMenu", "v_motus_ptm", function()
		spawnmenu.AddToolMenuOption("Options", "VerusMotus", "verusmotus_l", "Client Settings", nil, nil, function(panel)
			local v_motus_key_label = vgui.Create("DLabel", panel)
			v_motus_key_label:SetText("verus motus key:")
			panel:AddItem(v_motus_key_label)
			//
			local v_motus_key_binder = vgui.Create("DBinder", panel)
			v_motus_key_binder:SetConVar(v_motus_key_l)
			panel:AddItem(v_motus_key_binder)
			//
			v_motus_gender_cb = panel:ComboBox("Gender", v_motus_gender_l)
			v_motus_gender_cb:AddChoice("Male", "male")
			v_motus_gender_cb:AddChoice("Female", "female")
			v_motus_gender_cb:AddChoice("None", nil)
			//
			local v_motus_roll = vgui.Create("DCheckBoxLabel", panel)
			v_motus_roll:SetText("Rolling")
			v_motus_roll:SetConVar(v_motus_roll_l)
			panel:AddItem(v_motus_roll)
			//
			local v_motus_grab = vgui.Create("DCheckBoxLabel", panel)
			v_motus_grab:SetText("Grabbing")
			v_motus_grab:SetConVar(v_motus_grab_l)
			panel:AddItem(v_motus_grab)
			//
			local v_motus_walljump = vgui.Create("DCheckBoxLabel", panel)
			v_motus_walljump:SetText("Wall Jumping")
			v_motus_walljump:SetConVar(v_motus_walljump_l)
			panel:AddItem(v_motus_walljump)
			//
			local v_motus_falldamage = vgui.Create("DCheckBoxLabel", panel)
			v_motus_falldamage:SetText("Realistic Fall Damage")
			v_motus_falldamage:SetConVar(v_motus_falldamage_l)
			panel:AddItem(v_motus_falldamage)
			//
			local v_motus_falldamagedivider = vgui.Create("DNumSlider", panel)
			v_motus_falldamagedivider:SetText("Fall Damage Divider")
			v_motus_falldamagedivider:SetMin(0)
			v_motus_falldamagedivider:SetMax(20)
			v_motus_falldamagedivider:SetDecimals(2)
			v_motus_falldamagedivider:SetConVar(v_motus_falldamagedivider_l)
			panel:AddItem(v_motus_falldamagedivider)
			//
			local v_motus_steps = vgui.Create("DNumSlider", panel)
			v_motus_steps:SetText("Wall Run Steps")
			v_motus_steps:SetMin(0)
			v_motus_steps:SetMax(20)
			v_motus_steps:SetDecimals(0)
			v_motus_steps:SetConVar(v_motus_steps_l)
			panel:AddItem(v_motus_steps)
			//
			local v_motus_step_force = vgui.Create("DNumSlider", panel)
			v_motus_step_force:SetText("Wall Run Step Force")
			v_motus_step_force:SetMin(250)
			v_motus_step_force:SetMax(500)
			v_motus_step_force:SetDecimals(0)
			v_motus_step_force:SetConVar(v_motus_step_force_l)
			panel:AddItem(v_motus_step_force)
			//
			local v_motus_stepsafterwj = vgui.Create("DNumSlider", panel)
			v_motus_stepsafterwj:SetText("Wall Jump Step Refresh")
			v_motus_stepsafterwj:SetMin(0)
			v_motus_stepsafterwj:SetMax(20)
			v_motus_stepsafterwj:SetDecimals(0)
			v_motus_stepsafterwj:SetConVar(v_motus_stepsafterwj_l)
			panel:AddItem(v_motus_stepsafterwj)
		end)

		spawnmenu.AddToolMenuOption("Options", "VerusMotus", "verusmotus_g", "Server Settings", nil, nil, function(panel)
			local v_motus_serverside_dcbl = vgui.Create("DCheckBoxLabel", panel)
			v_motus_serverside_dcbl:SetText("Use server side variables")
			v_motus_serverside_dcbl:SetConVar(v_motus_serverside_g)
			panel:AddItem(v_motus_serverside_dcbl)
			//
			local v_motus_voices_dcbl = vgui.Create("DCheckBoxLabel", panel)
			v_motus_voices_dcbl:SetText("Voices")
			v_motus_voices_dcbl:SetConVar(v_motus_voices_g)
			panel:AddItem(v_motus_voices_dcbl)
			//
			local v_motus_roll = vgui.Create("DCheckBoxLabel", panel)
			v_motus_roll:SetText("Rolling")
			v_motus_roll:SetConVar(v_motus_roll_g)
			panel:AddItem(v_motus_roll)
			//
			local v_motus_grab = vgui.Create("DCheckBoxLabel", panel)
			v_motus_grab:SetText("Grabbing")
			v_motus_grab:SetConVar(v_motus_grab_g)
			panel:AddItem(v_motus_grab)
			//
			local v_motus_walljump = vgui.Create("DCheckBoxLabel", panel)
			v_motus_walljump:SetText("Wall Jumping")
			v_motus_walljump:SetConVar(v_motus_walljump_g)
			panel:AddItem(v_motus_walljump)
			//
			local v_motus_falldamage = vgui.Create("DCheckBoxLabel", panel)
			v_motus_falldamage:SetText("Realistic Fall Damage")
			v_motus_falldamage:SetConVar(v_motus_falldamage_g)
			panel:AddItem(v_motus_falldamage)
			//
			local v_motus_falldamagedivider = vgui.Create("DNumSlider", panel)
			v_motus_falldamagedivider:SetText("Fall Damage Divider")
			v_motus_falldamagedivider:SetMin(0)
			v_motus_falldamagedivider:SetMax(20)
			v_motus_falldamagedivider:SetDecimals(2)
			v_motus_falldamagedivider:SetConVar(v_motus_falldamagedivider_g)
			panel:AddItem(v_motus_falldamagedivider)
			//
			local v_motus_steps = vgui.Create("DNumSlider", panel)
			v_motus_steps:SetText("Wall Run Steps")
			v_motus_steps:SetMin(0)
			v_motus_steps:SetMax(20)
			v_motus_steps:SetDecimals(0)
			v_motus_steps:SetConVar(v_motus_steps_g)
			panel:AddItem(v_motus_steps)
			//
			local v_motus_step_force = vgui.Create("DNumSlider", panel)
			v_motus_step_force:SetText("Wall Run Step Force")
			v_motus_step_force:SetMin(250)
			v_motus_step_force:SetMax(500)
			v_motus_step_force:SetDecimals(0)
			v_motus_step_force:SetConVar(v_motus_step_force_g)
			panel:AddItem(v_motus_step_force)
			//
			local v_motus_stepsafterwj = vgui.Create("DNumSlider", panel)
			v_motus_stepsafterwj:SetText("Wall Jump Step Refresh")
			v_motus_stepsafterwj:SetMin(0)
			v_motus_stepsafterwj:SetMax(20)
			v_motus_stepsafterwj:SetDecimals(0)
			v_motus_stepsafterwj:SetConVar(v_motus_stepsafterwj_g)
			panel:AddItem(v_motus_stepsafterwj)
		end)
	end)
end