include("cvars.lua")

if CLIENT then
	hook.Add("PopulateToolMenu", "v_motus_ptm", function()
		spawnmenu.AddToolMenuOption("Options", "VerusMotus", "verusmotus_l", "Client Settings", nil, nil, function(panel)
			local v_motus_steps = vgui.Create("DNumSlider", panel)
			v_motus_steps:SetText("Wall Run Steps")
			v_motus_steps:SetMin(0)
			v_motus_steps:SetMax(20)
			v_motus_steps:SetDecimals(0)
			v_motus_steps:SetConVar(v_motus_steps_l)
			panel:AddItem(v_motus_steps)
			//
			local v_motus_step_force = vgui.Create("DNumSlider", panel)
			v_motus_step_force:SetText("Wall Run Step Force")
			v_motus_step_force:SetMin(250)
			v_motus_step_force:SetMax(500)
			v_motus_step_force:SetDecimals(0)
			v_motus_step_force:SetConVar(v_motus_step_force_l)
			panel:AddItem(v_motus_step_force)
		end)

		spawnmenu.AddToolMenuOption("Options", "VerusMotus", "verusmotus_g", "Server Settings", nil, nil, function(panel)
			local v_motus_serverside_dcbl = vgui.Create("DCheckBoxLabel", panel)
			v_motus_serverside_dcbl:SetText("Use server side variables")
			v_motus_serverside_dcbl:SetConVar(v_motus_serverside)
			panel:AddItem(v_motus_serverside_dcbl)
			//
			local v_motus_steps = vgui.Create("DNumSlider", panel)
			v_motus_steps:SetText("Wall Run Steps")
			v_motus_steps:SetMin(0)
			v_motus_steps:SetMax(20)
			v_motus_steps:SetDecimals(0)
			v_motus_steps:SetConVar(v_motus_steps_g)
			panel:AddItem(v_motus_steps)
			//
			local v_motus_step_force = vgui.Create("DNumSlider", panel)
			v_motus_step_force:SetText("Wall Run Step Force")
			v_motus_step_force:SetMin(250)
			v_motus_step_force:SetMax(500)
			v_motus_step_force:SetDecimals(0)
			v_motus_step_force:SetConVar(v_motus_step_force_g)
			panel:AddItem(v_motus_step_force)
		end)
	end)
end