CreateConVar("vmotus_rfd", 1, 0, "")
CreateConVar("vmotus_rfdNum", 9.5, 0, "")
CreateConVar("vmotus_rdr", 1, 0, "")
CreateConVar("vmotus_wrs", 3, 0, "")
CreateConVar("vmotus_wrsf", 275, 0, "")
CreateConVar("vmotus_wjs", 3, 0, "")
CreateConVar("vmotus_scream", 1, 0, "")
